"""baseline: mirror existing prisma schema

Revision ID: 8b9caba8c3dc
Revises: 
Create Date: 2026-09-17 20:53:42.359737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b9caba8c3dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_prisma_migrations')
    op.alter_column('allocation_results', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('allocation_results', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('allocation_results', 'computedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('allocation_results_userId_computedAt_idx', table_name='allocation_results')
    op.create_index('ix_allocation_results_userId_computedAt', 'allocation_results', ['userId', 'computedAt'], unique=False)
    op.drop_constraint('allocation_results_userId_fkey', 'allocation_results', type_='foreignkey')
    op.create_foreign_key(None, 'allocation_results', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('existing_debt', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('existing_debt', 'financialProfileId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('existing_debt', 'label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('existing_debt', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('existing_debt_financialProfileId_fkey', 'existing_debt', type_='foreignkey')
    op.create_foreign_key(None, 'existing_debt', 'financial_profile', ['financialProfileId'], ['id'], ondelete='CASCADE')
    op.alter_column('financial_profile', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('financial_profile', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('financial_profile', 'consentGivenAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('financial_profile', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('financial_profile', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('financial_profile_userId_key', table_name='financial_profile')
    op.create_unique_constraint(None, 'financial_profile', ['userId'])
    op.drop_constraint('financial_profile_userId_fkey', 'financial_profile', type_='foreignkey')
    op.create_foreign_key(None, 'financial_profile', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.add_column('fund_reference', sa.Column('aumCr', sa.Numeric(precision=12, scale=2), nullable=False))
    op.alter_column('fund_reference', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'schemeCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'schemeName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'amcName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'externalUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'lastSyncedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('fund_reference_category_idx', table_name='fund_reference')
    op.drop_index('fund_reference_schemeCode_key', table_name='fund_reference')
    op.create_index('ix_fund_reference_category', 'fund_reference', ['category'], unique=False)
    op.create_unique_constraint(None, 'fund_reference', ['schemeCode'])
    op.alter_column('gap_analysis_results', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('gap_analysis_results', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('gap_analysis_results', 'debtPriorityOrder',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('gap_analysis_results', 'computedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('gap_analysis_results_userId_computedAt_idx', table_name='gap_analysis_results')
    op.create_index('ix_gap_analysis_results_userId_computedAt', 'gap_analysis_results', ['userId', 'computedAt'], unique=False)
    op.drop_constraint('gap_analysis_results_userId_fkey', 'gap_analysis_results', type_='foreignkey')
    op.create_foreign_key(None, 'gap_analysis_results', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.add_column('insurance_plan_reference', sa.Column('claimSettlementRatioPct', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('insurance_plan_reference', sa.Column('avgClaimSettlementDays', sa.Integer(), nullable=False))
    op.alter_column('insurance_plan_reference', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'insurerName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'planName',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'indicativePremiumNote',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'keyFeatures',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'externalUrl',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'lastUpdatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insurance_plan_reference', 'sourceNote',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('insurance_plan_reference_planType_idx', table_name='insurance_plan_reference')
    op.create_index('ix_insurance_plan_reference_planType', 'insurance_plan_reference', ['planType'], unique=False)
    op.alter_column('insurance_profile', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_profile', 'userId',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('insurance_profile', 'consentGivenAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('insurance_profile', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insurance_profile', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('insurance_profile_userId_key', table_name='insurance_profile')
    op.create_unique_constraint(None, 'insurance_profile', ['userId'])
    op.drop_constraint('insurance_profile_userId_fkey', 'insurance_profile', type_='foreignkey')
    op.create_foreign_key(None, 'insurance_profile', 'users', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'hashedPassword',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updatedAt',
               existing_type=postgresql.TIMESTAMP(precision=3),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('users_email_key', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('users_email_key', 'users', ['email'], unique=True)
    op.alter_column('users', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('users', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'hashedPassword',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'insurance_profile', type_='foreignkey')
    op.create_foreign_key('insurance_profile_userId_fkey', 'insurance_profile', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'insurance_profile', type_='unique')
    op.create_index('insurance_profile_userId_key', 'insurance_profile', ['userId'], unique=True)
    op.alter_column('insurance_profile', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('insurance_profile', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insurance_profile', 'consentGivenAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('insurance_profile', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_profile', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_insurance_plan_reference_planType', table_name='insurance_plan_reference')
    op.create_index('insurance_plan_reference_planType_idx', 'insurance_plan_reference', ['planType'], unique=False)
    op.alter_column('insurance_plan_reference', 'sourceNote',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'lastUpdatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('insurance_plan_reference', 'externalUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'keyFeatures',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'indicativePremiumNote',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'planName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'insurerName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('insurance_plan_reference', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('insurance_plan_reference', 'avgClaimSettlementDays')
    op.drop_column('insurance_plan_reference', 'claimSettlementRatioPct')
    op.drop_constraint(None, 'gap_analysis_results', type_='foreignkey')
    op.create_foreign_key('gap_analysis_results_userId_fkey', 'gap_analysis_results', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_gap_analysis_results_userId_computedAt', table_name='gap_analysis_results')
    op.create_index('gap_analysis_results_userId_computedAt_idx', 'gap_analysis_results', ['userId', 'computedAt'], unique=False)
    op.alter_column('gap_analysis_results', 'computedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('gap_analysis_results', 'debtPriorityOrder',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('gap_analysis_results', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('gap_analysis_results', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'fund_reference', type_='unique')
    op.drop_index('ix_fund_reference_category', table_name='fund_reference')
    op.create_index('fund_reference_schemeCode_key', 'fund_reference', ['schemeCode'], unique=True)
    op.create_index('fund_reference_category_idx', 'fund_reference', ['category'], unique=False)
    op.alter_column('fund_reference', 'lastSyncedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('fund_reference', 'externalUrl',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'amcName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'schemeName',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'schemeCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fund_reference', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('fund_reference', 'aumCr')
    op.drop_constraint(None, 'financial_profile', type_='foreignkey')
    op.create_foreign_key('financial_profile_userId_fkey', 'financial_profile', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'financial_profile', type_='unique')
    op.create_index('financial_profile_userId_key', 'financial_profile', ['userId'], unique=True)
    op.alter_column('financial_profile', 'updatedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False)
    op.alter_column('financial_profile', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('financial_profile', 'consentGivenAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=True)
    op.alter_column('financial_profile', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('financial_profile', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'existing_debt', type_='foreignkey')
    op.create_foreign_key('existing_debt_financialProfileId_fkey', 'existing_debt', 'financial_profile', ['financialProfileId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('existing_debt', 'createdAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('existing_debt', 'label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('existing_debt', 'financialProfileId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('existing_debt', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'allocation_results', type_='foreignkey')
    op.create_foreign_key('allocation_results_userId_fkey', 'allocation_results', 'users', ['userId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('ix_allocation_results_userId_computedAt', table_name='allocation_results')
    op.create_index('allocation_results_userId_computedAt_idx', 'allocation_results', ['userId', 'computedAt'], unique=False)
    op.alter_column('allocation_results', 'computedAt',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=3),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('allocation_results', 'userId',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('allocation_results', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    # ### end Alembic commands ###
