import os

DEMO_MODE: bool = os.getenv("DEMO_MODE", "true").lower() == "true"

EMERGENCY_FUND_MULTIPLIER = 6
INCOME_REPLACEMENT_MULTIPLIER = 10
HEALTH_COVER_BASELINE = 500_000
HIGH_INTEREST_DEBT_THRESHOLD = 12

BASE_EQUITY_AGE_CONSTANT = 100
RISK_TOLERANCE_MULTIPLIERS = {
    "conservative": 0.8,
    "moderate": 1.0,
    "aggressive": 1.2,
}
SHORT_HORIZON_THRESHOLD = 3
SHORT_HORIZON_SHIFT = 20
GOLD_ALLOCATION_PCT = 10

FUND_EXAMPLES_PER_CATEGORY = 3
INSURANCE_EXAMPLES_PER_GAP_TYPE = 2
