import { useAuth } from "@/lib/auth";
import type { User } from "@/lib/types";

export type Language = User["preferred_language"];

export const languageOptions: Array<{ value: Language; label: string; short: string }> = [
  { value: "en", label: "English", short: "EN" },
  { value: "hi", label: "हिन्दी", short: "हि" },
  { value: "te", label: "తెలుగు", short: "తె" },
  { value: "ta", label: "தமிழ்", short: "த" },
];

const translations: Record<Language, Record<string, string>> = {
  en: {
    profile: "Profile", dashboard: "Dashboard", insurance: "Insurance", admin: "Admin", familyEngine: "Family protection engine",
    signOut: "Sign out", settings: "Profile & settings", language: "Language", indiaInr: "India / INR",
    footer: "SurakshaCFO provides educational estimates, not regulated financial advice. Always verify policy wording with a licensed advisor.",
    profileEyebrow: "Private financial map", profileTitle: "Make your family’s financial safety net visible.", profileDescription: "A four-minute profile turns scattered numbers into a clear order of protection: emergency fund, insurance gaps, then investable surplus.",
    family: "Family", income: "Income", liabilities: "Liabilities", protection: "Protection", continue: "Continue", back: "Back", buildMap: "Build my protection map", startOver: "Start over",
    step1Title: "Who are we protecting?", step2Title: "Map your earning engine", step3Title: "Make debt visible", step4Title: "What is already in place?", fullName: "Your full name", dateOfBirth: "Date of birth", yourAge: "Your age", cityTier: "City tier", maritalStatus: "Marital status", married: "Married", single: "Single", dependents: "Children or parents financially dependent on you", spouseName: "Spouse full name", spouseDob: "Spouse date of birth", spouseAge: "Spouse age", spouseEmployment: "Spouse employment", employment: "How do you earn?", annualIncome: "Your annual income (₹)", spouseIncome: "Spouse annual income (₹)", monthlyExpenses: "Monthly household expenses (₹)", annualBonus: "Annual bonus / variable income (₹)", homeLoan: "Home loan balance (₹)", otherLoans: "Car / personal loan balance (₹)", monthlyEmi: "Total monthly EMI (₹)", otherDebts: "Other outstanding debts (₹)", healthCover: "Current health cover (₹ lakh)", termCover: "Existing term cover (₹ crore)", emergencySavings: "Liquid emergency savings (₹)", investments: "Current investments (₹)", riskTolerance: "Investment risk tolerance", riskConservative: "Conservative — protect capital", riskModerate: "Moderate — balanced", riskAggressive: "Aggressive — growth first", investmentHorizon: "Investment horizon (years)",
    greeting: "Good morning", dashboardDescription: "Here’s the honest view of what your family has, what it needs, and what can be invested next.", reviewInsurance: "Review insurance options",
    protectionScore: "Protection score", termGap: "Term cover gap", healthGap: "Health cover gap", investableNext: "Investable next",
    profileKpis: "Profile KPI metrics", kpiNeutralNote: "Plain calculations only — no ranking or good/bad verdict.", emergencyCoverage: "Emergency fund coverage", runwayMonths: "Runway in months", termAdequacy: "Term cover adequacy", healthAdequacy: "Health cover adequacy", savingsRate: "Savings rate", debtToIncome: "Debt-to-income", coverLiabilities: "Cover-to-liabilities", liabilitiesIncome: "Liabilities-to-income", illustrativeThreshold: "Illustrative threshold: 40–50%, not advice", formula: "Formula",
    insuranceTitle: "Cover the gap, not the pitch.", insuranceDescription: "Shortlist illustrative Indian term and health plans against the needs in your family profile.",
    chatTitle: "Suraksha RAG guide", chatStatus: "Gemini · profile + indexed documents", chatPlaceholder: "Ask generally, or name plans to compare…", grounded: "GROUNDED", promptTerm: "Why do I need term insurance?", promptCompare: "Compare two named plans", promptCritical: "Should I add critical illness?", chatRule: "General questions use only your profile; named-plan questions use active indexed documents.",
    accountTitle: "Profile & settings", accountDescription: "Update your account preferences, security, and family financial details.", personalSettings: "Personal settings", displayName: "Display name", email: "Email address", preferredLanguage: "Preferred language", notifications: "Product and protection reminders", privacyMode: "Enhanced privacy mode", saveSettings: "Save settings",
    financialProfile: "Family financial profile", editProfile: "Edit financial details", profileReady: "Profile complete", profilePending: "Profile pending", security: "Security", currentPassword: "Current password", newPassword: "New password", confirmPassword: "Confirm new password", changePassword: "Change password",
  },
  hi: {
    profile: "प्रोफ़ाइल", dashboard: "डैशबोर्ड", insurance: "बीमा", admin: "एडमिन", familyEngine: "परिवार सुरक्षा इंजन",
    signOut: "साइन आउट", settings: "प्रोफ़ाइल और सेटिंग्स", language: "भाषा", indiaInr: "भारत / INR",
    footer: "SurakshaCFO शैक्षिक अनुमान देता है, विनियमित वित्तीय सलाह नहीं। खरीदने से पहले पॉलिसी की शर्तें सत्यापित करें।",
    profileEyebrow: "निजी वित्तीय मानचित्र", profileTitle: "अपने परिवार की वित्तीय सुरक्षा को स्पष्ट देखें।", profileDescription: "चार मिनट की प्रोफ़ाइल आपके आंकड़ों को सही क्रम देती है: आपात निधि, बीमा की कमी, फिर निवेश योग्य बचत।",
    family: "परिवार", income: "आय", liabilities: "देनदारियाँ", protection: "सुरक्षा", continue: "आगे बढ़ें", back: "पीछे", buildMap: "मेरा सुरक्षा मानचित्र बनाएं", startOver: "फिर से शुरू करें",
    step1Title: "हम किसकी सुरक्षा कर रहे हैं?", step2Title: "अपनी आय का नक्शा बनाएं", step3Title: "कर्ज स्पष्ट करें", step4Title: "पहले से क्या उपलब्ध है?", fullName: "आपका पूरा नाम", dateOfBirth: "जन्म तिथि", yourAge: "आपकी आयु", cityTier: "शहर श्रेणी", maritalStatus: "वैवाहिक स्थिति", married: "विवाहित", single: "अविवाहित", dependents: "आप पर आर्थिक रूप से निर्भर बच्चे या माता-पिता", spouseName: "जीवनसाथी का पूरा नाम", spouseDob: "जीवनसाथी की जन्म तिथि", spouseAge: "जीवनसाथी की आयु", spouseEmployment: "जीवनसाथी का रोजगार", employment: "आप कैसे कमाते हैं?", annualIncome: "आपकी वार्षिक आय (₹)", spouseIncome: "जीवनसाथी की वार्षिक आय (₹)", monthlyExpenses: "मासिक घरेलू खर्च (₹)", annualBonus: "वार्षिक बोनस / परिवर्तनीय आय (₹)", homeLoan: "होम लोन शेष (₹)", otherLoans: "कार / पर्सनल लोन शेष (₹)", monthlyEmi: "कुल मासिक EMI (₹)", otherDebts: "अन्य बकाया कर्ज (₹)", healthCover: "वर्तमान हेल्थ कवर (₹ लाख)", termCover: "मौजूदा टर्म कवर (₹ करोड़)", emergencySavings: "तरल आपात बचत (₹)", investments: "वर्तमान निवेश (₹)", riskTolerance: "निवेश जोखिम सहनशीलता", riskConservative: "रूढ़िवादी — पूंजी की सुरक्षा", riskModerate: "संतुलित — मध्यम जोखिम", riskAggressive: "आक्रामक — वृद्धि पहले", investmentHorizon: "निवेश अवधि (वर्ष)",
    greeting: "सुप्रभात", dashboardDescription: "देखें कि आपके परिवार के पास क्या है, क्या चाहिए और आगे कितना निवेश किया जा सकता है।", reviewInsurance: "बीमा विकल्प देखें",
    protectionScore: "सुरक्षा स्कोर", termGap: "टर्म कवर की कमी", healthGap: "हेल्थ कवर की कमी", investableNext: "निवेश योग्य राशि",
    profileKpis: "प्रोफ़ाइल KPI मेट्रिक्स", kpiNeutralNote: "केवल साधारण गणना — कोई रैंकिंग या अच्छा/बुरा निर्णय नहीं।", emergencyCoverage: "आपात निधि कवरेज", runwayMonths: "रनवे के महीने", termAdequacy: "टर्म कवर पर्याप्तता", healthAdequacy: "हेल्थ कवर पर्याप्तता", savingsRate: "बचत दर", debtToIncome: "कर्ज-से-आय", coverLiabilities: "कवर-से-देनदारी", liabilitiesIncome: "देनदारी-से-आय", illustrativeThreshold: "उदाहरण सीमा: 40–50%, सलाह नहीं", formula: "फ़ॉर्मूला",
    insuranceTitle: "बिक्री नहीं, अपनी सुरक्षा की कमी पूरी करें।", insuranceDescription: "अपने परिवार प्रोफ़ाइल की जरूरतों के अनुसार भारतीय टर्म और हेल्थ प्लान देखें।",
    chatTitle: "Suraksha RAG मार्गदर्शक", chatStatus: "Gemini · प्रोफ़ाइल + इंडेक्स दस्तावेज़", chatPlaceholder: "सामान्य प्रश्न पूछें या तुलना के लिए प्लान का नाम दें…", grounded: "स्रोत-आधारित", promptTerm: "मुझे टर्म इंश्योरेंस क्यों चाहिए?", promptCompare: "दो नामित प्लान की तुलना करें", promptCritical: "क्या मुझे क्रिटिकल इलनेस कवर जोड़ना चाहिए?", chatRule: "सामान्य प्रश्न केवल आपके प्रोफ़ाइल का उपयोग करते हैं; नामित प्लान के प्रश्न सक्रिय दस्तावेज़ों का उपयोग करते हैं।",
    accountTitle: "प्रोफ़ाइल और सेटिंग्स", accountDescription: "अपनी खाता पसंद, सुरक्षा और परिवार के वित्तीय विवरण अपडेट करें।", personalSettings: "व्यक्तिगत सेटिंग्स", displayName: "दिखने वाला नाम", email: "ईमेल पता", preferredLanguage: "पसंदीदा भाषा", notifications: "उत्पाद और सुरक्षा रिमाइंडर", privacyMode: "बेहतर गोपनीयता मोड", saveSettings: "सेटिंग्स सहेजें",
    financialProfile: "परिवार वित्तीय प्रोफ़ाइल", editProfile: "वित्तीय विवरण बदलें", profileReady: "प्रोफ़ाइल पूरी", profilePending: "प्रोफ़ाइल बाकी", security: "सुरक्षा", currentPassword: "वर्तमान पासवर्ड", newPassword: "नया पासवर्ड", confirmPassword: "नया पासवर्ड दोबारा", changePassword: "पासवर्ड बदलें",
  },
  te: {
    profile: "ప్రొఫైల్", dashboard: "డ్యాష్‌బోర్డ్", insurance: "బీమా", admin: "అడ్మిన్", familyEngine: "కుటుంబ రక్షణ ఇంజిన్",
    signOut: "సైన్ అవుట్", settings: "ప్రొఫైల్ & సెట్టింగ్స్", language: "భాష", indiaInr: "భారతదేశం / INR",
    footer: "SurakshaCFO విద్యాపరమైన అంచనాలను మాత్రమే ఇస్తుంది. కొనుగోలు ముందు పాలసీ నిబంధనలను ధృవీకరించండి.",
    profileEyebrow: "ప్రైవేట్ ఆర్థిక పటం", profileTitle: "మీ కుటుంబ ఆర్థిక భద్రతను స్పష్టంగా చూడండి.", profileDescription: "నాలుగు నిమిషాల ప్రొఫైల్ మీ సంఖ్యలను సరైన క్రమంలో ఉంచుతుంది: అత్యవసర నిధి, బీమా లోటు, ఆపై పెట్టుబడి మిగులు.",
    family: "కుటుంబం", income: "ఆదాయం", liabilities: "బాధ్యతలు", protection: "రక్షణ", continue: "కొనసాగించండి", back: "వెనుకకు", buildMap: "నా రక్షణ పటం రూపొందించండి", startOver: "మళ్లీ ప్రారంభించండి",
    step1Title: "మనం ఎవరిని రక్షిస్తున్నాం?", step2Title: "మీ ఆదాయ పటాన్ని రూపొందించండి", step3Title: "అప్పులను స్పష్టంగా చూడండి", step4Title: "ఇప్పటికే ఏమి ఉంది?", fullName: "మీ పూర్తి పేరు", dateOfBirth: "పుట్టిన తేదీ", yourAge: "మీ వయస్సు", cityTier: "నగర శ్రేణి", maritalStatus: "వైవాహిక స్థితి", married: "వివాహితులు", single: "అవివాహితులు", dependents: "మీపై ఆర్థికంగా ఆధారపడిన పిల్లలు లేదా తల్లిదండ్రులు", spouseName: "జీవిత భాగస్వామి పూర్తి పేరు", spouseDob: "జీవిత భాగస్వామి పుట్టిన తేదీ", spouseAge: "జీవిత భాగస్వామి వయస్సు", spouseEmployment: "జీవిత భాగస్వామి ఉద్యోగం", employment: "మీరు ఎలా సంపాదిస్తారు?", annualIncome: "మీ వార్షిక ఆదాయం (₹)", spouseIncome: "జీవిత భాగస్వామి వార్షిక ఆదాయం (₹)", monthlyExpenses: "నెలవారీ కుటుంబ ఖర్చులు (₹)", annualBonus: "వార్షిక బోనస్ / మారే ఆదాయం (₹)", homeLoan: "హోమ్ లోన్ బాకీ (₹)", otherLoans: "కారు / వ్యక్తిగత లోన్ బాకీ (₹)", monthlyEmi: "మొత్తం నెలవారీ EMI (₹)", otherDebts: "ఇతర బాకీలు (₹)", healthCover: "ప్రస్తుత హెల్త్ కవర్ (₹ లక్షలు)", termCover: "ప్రస్తుత టర్మ్ కవర్ (₹ కోట్లు)", emergencySavings: "తక్షణ అత్యవసర పొదుపు (₹)", investments: "ప్రస్తుత పెట్టుబడులు (₹)", riskTolerance: "పెట్టుబడి రిస్క్ సహనం", riskConservative: "సంప్రదాయ — మూలధన రక్షణ", riskModerate: "మధ్యస్థ — సమతుల్యం", riskAggressive: "దూకుడు — వృద్ధికి ప్రాధాన్యం", investmentHorizon: "పెట్టుబడి కాలవ్యవధి (సంవత్సరాలు)",
    greeting: "శుభోదయం", dashboardDescription: "మీ కుటుంబానికి ఏముంది, ఏమి అవసరం, తర్వాత ఎంత పెట్టుబడి పెట్టవచ్చో చూడండి.", reviewInsurance: "బీమా ఎంపికలు చూడండి",
    protectionScore: "రక్షణ స్కోర్", termGap: "టర్మ్ కవర్ లోటు", healthGap: "హెల్త్ కవర్ లోటు", investableNext: "పెట్టుబడి చేయగల మొత్తం",
    profileKpis: "ప్రొఫైల్ KPI మెట్రిక్స్", kpiNeutralNote: "సాధారణ లెక్కలు మాత్రమే — ర్యాంకింగ్ లేదా మంచి/చెడు తీర్పు లేదు.", emergencyCoverage: "అత్యవసర నిధి కవరేజ్", runwayMonths: "రన్‌వే నెలలు", termAdequacy: "టర్మ్ కవర్ సమృద్ధి", healthAdequacy: "హెల్త్ కవర్ సమృద్ధి", savingsRate: "పొదుపు రేటు", debtToIncome: "అప్పు-ఆదాయం", coverLiabilities: "కవర్-బాధ్యతలు", liabilitiesIncome: "బాధ్యతలు-ఆదాయం", illustrativeThreshold: "ఉదాహరణ పరిమితి: 40–50%, సలహా కాదు", formula: "సూత్రం",
    insuranceTitle: "ప్రచారం కాదు, లోటును కవర్ చేయండి.", insuranceDescription: "మీ కుటుంబ ప్రొఫైల్ అవసరాలకు అనుగుణంగా భారతీయ టర్మ్, హెల్త్ ప్లాన్‌లను చూడండి.",
    chatTitle: "Suraksha RAG గైడ్", chatStatus: "Gemini · ప్రొఫైల్ + ఇండెక్స్ పత్రాలు", chatPlaceholder: "సాధారణంగా అడగండి లేదా పోలిక కోసం ప్లాన్ పేరు చెప్పండి…", grounded: "ఆధారిత", promptTerm: "నాకు టర్మ్ ఇన్సూరెన్స్ ఎందుకు అవసరం?", promptCompare: "పేరు చెప్పిన రెండు ప్లాన్‌లను పోల్చండి", promptCritical: "క్రిటికల్ ఇల్నెస్ కవర్ జోడించాలా?", chatRule: "సాధారణ ప్రశ్నలు మీ ప్రొఫైల్‌ను మాత్రమే ఉపయోగిస్తాయి; పేరు చెప్పిన ప్లాన్ ప్రశ్నలు సక్రియ పత్రాలను ఉపయోగిస్తాయి.",
    accountTitle: "ప్రొఫైల్ & సెట్టింగ్స్", accountDescription: "ఖాతా ప్రాధాన్యతలు, భద్రత, కుటుంబ ఆర్థిక వివరాలను మార్చండి.", personalSettings: "వ్యక్తిగత సెట్టింగ్స్", displayName: "ప్రదర్శన పేరు", email: "ఈమెయిల్ చిరునామా", preferredLanguage: "ఇష్టమైన భాష", notifications: "ఉత్పత్తి మరియు రక్షణ రిమైండర్లు", privacyMode: "మెరుగైన గోప్యత మోడ్", saveSettings: "సెట్టింగ్స్ సేవ్ చేయండి",
    financialProfile: "కుటుంబ ఆర్థిక ప్రొఫైల్", editProfile: "ఆర్థిక వివరాలు మార్చండి", profileReady: "ప్రొఫైల్ పూర్తి", profilePending: "ప్రొఫైల్ పెండింగ్", security: "భద్రత", currentPassword: "ప్రస్తుత పాస్‌వర్డ్", newPassword: "కొత్త పాస్‌వర్డ్", confirmPassword: "కొత్త పాస్‌వర్డ్ నిర్ధారించండి", changePassword: "పాస్‌వర్డ్ మార్చండి",
  },
  ta: {
    profile: "சுயவிவரம்", dashboard: "டாஷ்போர்டு", insurance: "காப்பீடு", admin: "நிர்வாகம்", familyEngine: "குடும்ப பாதுகாப்பு இயந்திரம்",
    signOut: "வெளியேறு", settings: "சுயவிவரம் & அமைப்புகள்", language: "மொழி", indiaInr: "இந்தியா / INR",
    footer: "SurakshaCFO கல்வி மதிப்பீடுகளை மட்டுமே வழங்குகிறது. வாங்குவதற்கு முன் பாலிசி விதிகளை சரிபார்க்கவும்.",
    profileEyebrow: "தனிப்பட்ட நிதி வரைபடம்", profileTitle: "உங்கள் குடும்ப நிதி பாதுகாப்பை தெளிவாகப் பாருங்கள்.", profileDescription: "நான்கு நிமிட சுயவிவரம் உங்கள் எண்களை சரியான வரிசையில் வைக்கிறது: அவசர நிதி, காப்பீட்டு இடைவெளி, பின்னர் முதலீட்டு மீதம்.",
    family: "குடும்பம்", income: "வருமானம்", liabilities: "கடன்கள்", protection: "பாதுகாப்பு", continue: "தொடரவும்", back: "பின்செல்", buildMap: "என் பாதுகாப்பு வரைபடத்தை உருவாக்கு", startOver: "மீண்டும் தொடங்கு",
    step1Title: "நாம் யாரை பாதுகாக்கிறோம்?", step2Title: "உங்கள் வருமானத்தை வரைபடமாக்குங்கள்", step3Title: "கடனை தெளிவாகப் பாருங்கள்", step4Title: "ஏற்கனவே என்ன உள்ளது?", fullName: "உங்கள் முழுப் பெயர்", dateOfBirth: "பிறந்த தேதி", yourAge: "உங்கள் வயது", cityTier: "நகர வகை", maritalStatus: "திருமண நிலை", married: "திருமணமானவர்", single: "திருமணமாகாதவர்", dependents: "உங்களை நிதியாக சார்ந்த குழந்தைகள் அல்லது பெற்றோர்", spouseName: "துணையின் முழுப் பெயர்", spouseDob: "துணையின் பிறந்த தேதி", spouseAge: "துணையின் வயது", spouseEmployment: "துணையின் வேலை", employment: "நீங்கள் எப்படி வருமானம் ஈட்டுகிறீர்கள்?", annualIncome: "உங்கள் ஆண்டு வருமானம் (₹)", spouseIncome: "துணையின் ஆண்டு வருமானம் (₹)", monthlyExpenses: "மாத குடும்ப செலவுகள் (₹)", annualBonus: "ஆண்டு போனஸ் / மாறும் வருமானம் (₹)", homeLoan: "வீட்டுக் கடன் இருப்பு (₹)", otherLoans: "கார் / தனிநபர் கடன் இருப்பு (₹)", monthlyEmi: "மொத்த மாத EMI (₹)", otherDebts: "மற்ற நிலுவைக் கடன்கள் (₹)", healthCover: "தற்போதைய ஹெல்த் கவர் (₹ லட்சம்)", termCover: "தற்போதைய டெர்ம் கவர் (₹ கோடி)", emergencySavings: "உடனடி அவசர சேமிப்பு (₹)", investments: "தற்போதைய முதலீடுகள் (₹)", riskTolerance: "முதலீட்டு இடர் சகிப்புத்தன்மை", riskConservative: "பழமைவாதம் — மூலதனப் பாதுகாப்பு", riskModerate: "மிதமானது — சமநிலை", riskAggressive: "தீவிரம் — வளர்ச்சிக்கு முன்னுரிமை", investmentHorizon: "முதலீட்டு காலம் (ஆண்டுகள்)",
    greeting: "காலை வணக்கம்", dashboardDescription: "உங்கள் குடும்பத்திடம் என்ன உள்ளது, என்ன தேவை, அடுத்து எவ்வளவு முதலீடு செய்யலாம் என்பதைக் காணுங்கள்.", reviewInsurance: "காப்பீட்டு விருப்பங்களைப் பாருங்கள்",
    protectionScore: "பாதுகாப்பு மதிப்பெண்", termGap: "டெர்ம் கவர் இடைவெளி", healthGap: "ஹெல்த் கவர் இடைவெளி", investableNext: "முதலீடு செய்யக்கூடிய தொகை",
    profileKpis: "சுயவிவர KPI அளவுகள்", kpiNeutralNote: "எளிய கணக்குகள் மட்டும் — தரவரிசை அல்லது நல்லது/கெட்டது தீர்ப்பு இல்லை.", emergencyCoverage: "அவசர நிதி கவரேஜ்", runwayMonths: "ரன்வே மாதங்கள்", termAdequacy: "டெர்ம் கவர் போதுமானது", healthAdequacy: "ஹெல்த் கவர் போதுமானது", savingsRate: "சேமிப்பு விகிதம்", debtToIncome: "கடன்-வருமானம்", coverLiabilities: "கவர்-கடன்கள்", liabilitiesIncome: "கடன்கள்-வருமானம்", illustrativeThreshold: "எடுத்துக்காட்டு வரம்பு: 40–50%, ஆலோசனை அல்ல", formula: "சூத்திரம்",
    insuranceTitle: "விற்பனை பேச்சல்ல, இடைவெளியை கவர் செய்யுங்கள்.", insuranceDescription: "உங்கள் குடும்ப விவரத் தேவைகளுக்கு ஏற்ப இந்திய டெர்ம் மற்றும் ஹெல்த் திட்டங்களைப் பாருங்கள்.",
    chatTitle: "Suraksha RAG வழிகாட்டி", chatStatus: "Gemini · விவரம் + ஆவணங்கள்", chatPlaceholder: "பொதுவாக கேளுங்கள் அல்லது ஒப்பிட திட்டப் பெயரைச் சொல்லுங்கள்…", grounded: "ஆதாரத்துடன்", promptTerm: "எனக்கு டெர்ம் காப்பீடு ஏன் தேவை?", promptCompare: "பெயரிட்ட இரண்டு திட்டங்களை ஒப்பிடுங்கள்", promptCritical: "கிரிட்டிக்கல் இல்னஸ் கவர் சேர்க்க வேண்டுமா?", chatRule: "பொது கேள்விகள் உங்கள் விவரத்தை மட்டுமே பயன்படுத்தும்; பெயரிட்ட திட்ட கேள்விகள் செயலில் உள்ள ஆவணங்களைப் பயன்படுத்தும்.",
    accountTitle: "சுயவிவரம் & அமைப்புகள்", accountDescription: "கணக்கு விருப்பங்கள், பாதுகாப்பு மற்றும் குடும்ப நிதி விவரங்களை மாற்றவும்.", personalSettings: "தனிப்பட்ட அமைப்புகள்", displayName: "காட்சி பெயர்", email: "மின்னஞ்சல் முகவரி", preferredLanguage: "விருப்ப மொழி", notifications: "தயாரிப்பு மற்றும் பாதுகாப்பு நினைவூட்டல்கள்", privacyMode: "மேம்பட்ட தனியுரிமை முறை", saveSettings: "அமைப்புகளை சேமி",
    financialProfile: "குடும்ப நிதி சுயவிவரம்", editProfile: "நிதி விவரங்களை மாற்று", profileReady: "சுயவிவரம் முடிந்தது", profilePending: "சுயவிவரம் நிலுவையில்", security: "பாதுகாப்பு", currentPassword: "தற்போதைய கடவுச்சொல்", newPassword: "புதிய கடவுச்சொல்", confirmPassword: "புதிய கடவுச்சொல்லை உறுதிப்படுத்து", changePassword: "கடவுச்சொல்லை மாற்று",
  },
};

export function useI18n() {
  const { user, updateSettings } = useAuth();
  const language = user?.preferred_language ?? "en";
  const t = (key: string) => translations[language][key] ?? translations.en[key] ?? key;
  const setLanguage = (nextLanguage: Language) => updateSettings({ preferred_language: nextLanguage });
  return { language, languageOptions, setLanguage, t };
}