import type { ProfileResponse } from "@/lib/types";

export const SAMPLE_PROFILE_RESPONSE: ProfileResponse = {
  profile: {
    id: "sample",
    full_name: "Aarav Mehta",
    dob: "1990-06-12",
    age: 35,
    city_tier: "tier_1",
    marital_status: "married",
    dependents: 3,
    spouse_full_name: "Ananya Mehta",
    spouse_dob: "1992-09-18",
    spouse_age: 33,
    spouse_employment_type: "mnc",
    employment_type: "mnc",
    annual_income: 2400000,
    spouse_income: 900000,
    monthly_expenses: 85000,
    annual_bonus: 300000,
    home_loan: 6500000,
    other_loans: 450000,
    monthly_emi: 58000,
    other_debts: 0,
    current_health_cover_lakh: 5,
    existing_term_cover_crore: 0.5,
    emergency_savings: 300000,
    current_investments: 1200000,
  },
  analysis: {
    annual_household_income: 3600000,
    annual_expenses: 1020000,
    annual_emi: 696000,
    total_liabilities: 6950000,
    annual_surplus_before_protection: 1884000,
    annual_insurance_budget: 181250,
    investable_surplus: 1702750,
    recommended_term_cover_crore: 4.3,
    term_gap_crore: 3.8,
    recommended_health_cover_lakh: 21,
    health_gap_lakh: 16,
    emergency_goal: 510000,
    emergency_gap: 210000,
    emergency_months: 3.5,
    kpis: {
      emergency_coverage_pct: 58.8,
      runway_months: 3.5,
      term_cover_adequacy_pct: 11.6,
      health_cover_adequacy_pct: 23.8,
      savings_rate_pct: 52.3,
      debt_to_income_pct: 19.3,
      cover_to_liabilities_ratio: 0.72,
      liabilities_to_income_multiple: 1.93,
    },
    protection_score: 43,
    score_label: "Needs attention",
    formula_notes: [
      "Term cover = 15× combined earned income + total liabilities − existing term cover.",
      "Health baseline = 10L + family-size and city adjustment, capped at 25L.",
      "Emergency fund target = 6× monthly household expenses before investing surplus.",
    ],
    disclaimer:
      "Educational estimates only. They are not financial, tax, medical, or insurance advice. Verify policy terms, exclusions, underwriting, claim experience, and premiums with a licensed advisor before buying.",
  },
  plans: [
    {
      id: "term-1",
      category: "term",
      name: "Click 2 Protect Super",
      provider: "HDFC Life",
      csr: "99.2%",
      annual_premium_from: 18500,
      cover_label: "Illustrative term cover",
      highlights: ["Flexible payout options", "Income replacement focus", "Optional riders"],
      fit: "Best for income replacement and long-term family protection",
    },
    {
      id: "term-2",
      category: "term",
      name: "iProtect Smart",
      provider: "ICICI Prudential",
      csr: "98.3%",
      annual_premium_from: 17200,
      cover_label: "Illustrative term cover",
      highlights: ["Multiple claim payout choices", "Terminal illness benefit", "Digital servicing"],
      fit: "A lower-premium option to compare with your protection gap",
    },
    {
      id: "health-1",
      category: "health",
      name: "Optima Secure",
      provider: "HDFC ERGO",
      csr: "98.6%",
      annual_premium_from: 26500,
      cover_label: "Illustrative family floater",
      highlights: ["Restore benefit", "No room-rent cap", "Super top-up compatible"],
      fit: "Strong floater baseline for growing families",
    },
    {
      id: "health-2",
      category: "health",
      name: "Care Supreme",
      provider: "Care Health",
      csr: "96.6%",
      annual_premium_from: 22800,
      cover_label: "Illustrative family floater",
      highlights: ["Unlimited recharge", "Wellness benefits", "Wide hospital network"],
      fit: "Value-led cover when the emergency fund is still being built",
    },
  ],
};

export const formatINR = (value: number, compact = false) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: compact ? 1 : 0,
    notation: compact ? "compact" : "standard",
  }).format(value);