import type { ProfileResponse } from "@/lib/types";

export const SAMPLE_PROFILE_RESPONSE: ProfileResponse = {
  profile: {
    id: "sample",
    full_name: "Aarav Mehta",
    dob: "1990-06-12",
    age: 35,
    city_tier: "tier_1",
    marital_status: "married",
    dependents: 3,
    spouse_full_name: "Ananya Mehta",
    spouse_dob: "1992-09-18",
    spouse_age: 33,
    spouse_employment_type: "mnc",
    employment_type: "mnc",
    annual_income: 2400000,
    spouse_income: 900000,
    monthly_expenses: 85000,
    annual_bonus: 300000,
    home_loan: 6500000,
    other_loans: 450000,
    monthly_emi: 58000,
    other_debts: 0,
    current_health_cover_lakh: 5,
    existing_term_cover_crore: 0.5,
    emergency_savings: 300000,
    current_investments: 1200000,
  },
  analysis: {
    annual_household_income: 3600000,
    annual_expenses: 1020000,
    annual_emi: 696000,
    total_liabilities: 6950000,
    annual_surplus_before_protection: 1884000,
    annual_insurance_budget: 181250,
    investable_surplus: 1702750,
    recommended_term_cover_crore: 4.3,
    term_gap_crore: 3.8,
    recommended_health_cover_lakh: 21,
    health_gap_lakh: 16,
    emergency_goal: 510000,
    emergency_gap: 210000,
    emergency_months: 3.5,
    kpis: {
      emergency_coverage_pct: 58.8,
      runway_months: 3.5,
      term_cover_adequacy_pct: 11.6,
      health_cover_adequacy_pct: 23.8,
      savings_rate_pct: 52.3,
      debt_to_income_pct: 19.3,
      cover_to_liabilities_ratio: 0.72,
      liabilities_to_income_multiple: 1.93,
    },
    protection_score: 43,
    score_label: "Needs attention",
    formula_notes: [
      "Term cover = 15× combined earned income + total liabilities − existing term cover.",
      "Health baseline = 10L + family-size and city adjustment, capped at 25L.",
      "Emergency fund target = 6× monthly household expenses before investing surplus.",
    ],
    disclaimer:
      "Educational estimates only. They are not financial, tax, medical, or insurance advice. Verify policy terms, exclusions, underwriting, claim experience, and premiums with a licensed advisor before buying.",
  },
};

export const formatINR = (value: number, compact = false) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: compact ? 1 : 0,
    notation: compact ? "compact" : "standard",
  }).format(value);